### ISSUE TITLE
TypeError: acf() got an unexpected keyword argument 'unbiased'

### ISSUE THREAD

**Issue by GermanCamargoOrtega** [cellgeometry/heteromotility#4]
Hi guys, I hope this email finds you well. I am trying to run the software with the demo data and get an error regarding the acf() function.
Please find attached the log below. Could you please let me know what is going on here? Many thanks in advance and best wishes.

(heteromotility_env) PS E:\GC\heteromotility\demo> heteromotility \demo\results --tracksX rw_x.csv --tracksY rw_y.csv --output_suffix results
Tracking  rw_x.csv
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\heteromotility_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\heteromotility_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\heteromotility_env\Scripts\heteromotility.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\heteromotility_env\lib\site-packages\heteromotility\command_line.py", line 4, in cli
    heteromotility.main()
  File "C:\ProgramData\Anaconda3\envs\heteromotility_env\lib\site-packages\heteromotility\heteromotility.py", line 127, in main
    rwf = RWFeatures(cp.cell_ids, gf)
  File "C:\ProgramData\Anaconda3\envs\heteromotility_env\lib\site-packages\heteromotility\hmstats.py", line 706, in __init__
    self.autocorr, self.qstats, self.pvals = self.autocorr_all(cell_ids, max_tau = self.autocorr_max_tau)
  File "C:\ProgramData\Anaconda3\envs\heteromotility_env\lib\site-packages\heteromotility\hmstats.py", line 1145, in autocorr_all
    ac, q, p = acf(X, unbiased = True, nlags = (max_tau+1), qstat=True)
TypeError: acf() got an unexpected keyword argument 'unbiased'

**Comment by Jose-Verdu-Diaz** [comment]
I have the same issue. It seems like the "unbiased" argument of statsmodels.tsa.stattools.acf() has been renamed to "adjusted". I'm working on a fork and will submit a pull request as soon as I have it.

**Comment by jacobkimmel** [comment]
Closed by #5
